# Generated by Django 4.2.4 on 2023-08-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='completed',
        ),
    ]
